{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stac-browser.fullname" . }}
  namespace: {{ include "stac-browser.namespace" . }}
  labels:
    {{- include "stac-browser.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.commonAnnotations) .Values.ingress.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.tlsSecretName | default (printf "%s-tls" .Values.ingress.hostname) }}
    {{- end }}
    {{- with .Values.ingress.extraTls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "stac-browser.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    {{- with .Values.ingress.extraHosts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
