apiVersion: v1
kind: Service
metadata:
  name: {{ include "stac-browser.fullname" . }}
  namespace: {{ include "stac-browser.namespace" . }}
  labels:
    {{- include "stac-browser.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.commonAnnotations) .Values.service.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    {{- with .Values.service.extraPorts }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "stac-browser.selectorLabels" . | nindent 4 }}
